window.serviceCatalog = {
  detailDefaults: {
    badges: ["Experienced team", "Clear service scope", "Quality checked"],
    facts: [
      { value: "7+", label: "Years expertise" },
      { value: "24/7", label: "Booking support" },
      { value: "Qatar", label: "Service coverage" },
    ],
    spotlight: {
      kicker: "Trusted local service",
      title: "Professional property care with clear communication at every step.",
      copy: "Support for homes, villas, apartments, offices, and commercial spaces across Qatar.",
    },
    steps: [
      "Tell us about your property and the service you need.",
      "We confirm the scope, timing, and recommended service plan.",
      "Our team completes the work and shares practical after-care guidance.",
    ],
    ctaLabel: "Request a quote",
  },
  categories: [
    {
      id: "cleaning",
      label: "Cleaning services",
      eyebrow: "Everyday property care",
      description: "Routine and deep cleaning for villas, apartments, and majlis spaces, delivered with a careful room-by-room approach.",
      background: "https://images.pexels.com/photos/3768914/pexels-photo-3768914.jpeg?auto=compress&cs=tinysrgb&w=1600",
      backgroundAlt: "Professional cleaning service in a modern home",
      detailDefaults: {
        badges: ["Room-by-room care", "Flexible scheduling", "Final quality check"],
        spotlight: {
          kicker: "Careful property cleaning",
          title: "A cleaner, more comfortable space with a clear plan from start to finish.",
          copy: "Suitable for villas, apartments, majlis rooms, and regularly maintained living spaces.",
        },
        steps: [
          "Tell us about your property, rooms, and preferred service time.",
          "We confirm the cleaning scope and prepare the right team and equipment.",
          "Our team cleans each agreed area, completes a final check, and shares care guidance.",
        ],
        ctaLabel: "Request a cleaning quote",
      },
      services: [
        {
          slug: "villa-cleaning",
          title: "Villa Cleaning",
          category: "Cleaning services",
          image: "https://images.pexels.com/photos/3768914/pexels-photo-3768914.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/villa-cleaning-hq.png",
          summary: "Complete interior cleaning for villas, majlis rooms, kitchens, bathrooms, and daily living areas.",
          includes: ["Room-by-room dusting", "Floor mopping and vacuuming", "Kitchen and bathroom wipe-down", "Balcony and high-touch surface cleaning"],
        },
        {
          slug: "apartment-cleaning",
          title: "Apartment Cleaning",
          category: "Cleaning services",
          image: "https://images.pexels.com/photos/8055198/pexels-photo-8055198.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Reliable apartment cleaning for compact homes, family flats, and rental handovers across Qatar.",
          includes: ["Bedroom and living area cleaning", "Kitchen counter cleaning", "Bathroom sanitising", "Trash removal and finishing checks"],
        },
        {
          slug: "majlis-cleaning",
          title: "Majlis Cleaning",
          category: "Cleaning services",
          image: "https://images.pexels.com/photos/4401538/pexels-photo-4401538.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Careful cleaning for majlis spaces, seating areas, cushions, carpets, and guest-ready interiors.",
          includes: ["Soft furnishing vacuuming", "Surface dusting", "Floor care", "Detail cleaning before guest visits"],
          badges: ["Majlis seating care", "Fabric-safe cleaning", "Guest-ready finish"],
          facts: [
            { value: "2-4h", label: "Typical visit" },
            { value: "Soft", label: "Fabric-safe care" },
            { value: "Qatar", label: "Home service" },
          ],
          spotlight: {
            kicker: "Majlis-ready finish",
            title: "Fresh seating, cushions, carpets, and guest areas cleaned with care.",
            copy: "Ideal before family visits, gatherings, and regular majlis refreshes.",
          },
          steps: [
            "We review the majlis layout, seating fabric, cushions, carpets, and high-touch surfaces.",
            "Technicians vacuum, dust, spot-clean, and refresh the guest area with suitable methods.",
            "We complete a final check so the majlis is tidy, comfortable, and guest-ready.",
          ],
        },
        {
          slug: "deep-cleaning",
          title: "Deep Cleaning",
          category: "Cleaning services",
          image: "https://images.pexels.com/photos/3616735/pexels-photo-3616735.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "A detailed cleaning visit for move-in, move-out, post-renovation, or seasonal refresh needs.",
          includes: ["Detailed dust removal", "Hard-to-reach areas", "Floor scrubbing", "Final inspection walkthrough"],
        },
      ],
    },
    {
      id: "specialised",
      label: "Specialised Cleaning",
      eyebrow: "Targeted hygiene care",
      description: "Focused care for sofas, carpets, mattresses, and water tanks using methods suited to each material and space.",
      background: "https://images.pexels.com/photos/30238384/pexels-photo-30238384.jpeg?auto=compress&cs=tinysrgb&w=1600",
      backgroundAlt: "Technician cleaning upholstery",
      detailDefaults: {
        badges: ["Material-aware methods", "Targeted stain care", "Clear drying guidance"],
        spotlight: {
          kicker: "Focused hygiene care",
          title: "Purposeful cleaning selected for the material, condition, and everyday use of each item.",
          copy: "Ideal for upholstery, carpets, mattresses, and other areas that need focused attention.",
        },
        steps: [
          "We review the material, condition, stains, and access around the item or area.",
          "The team selects a suitable cleaning method and completes the agreed treatment.",
          "We check the finish and explain drying times and practical after-care.",
        ],
        ctaLabel: "Request a specialist quote",
      },
      services: [
        {
          slug: "sofa-cleaning",
          title: "Sofa Cleaning",
          category: "Specialised Cleaning",
          image: "https://images.pexels.com/photos/30238384/pexels-photo-30238384.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/sofa-cleaning-hq.png",
          summary: "Fabric-safe sofa cleaning for stains, dust, odour, and everyday upholstery freshness.",
          includes: ["Fabric inspection", "Vacuum extraction", "Spot treatment", "Drying guidance"],
        },
        {
          slug: "carpet-cleaning",
          title: "Carpet Cleaning",
          category: "Specialised Cleaning",
          image: "https://images.pexels.com/photos/32155482/pexels-photo-32155482.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Professional carpet care for homes, offices, majlis spaces, and high-traffic areas.",
          includes: ["Vacuuming", "Spot cleaning", "Machine cleaning", "Post-cleaning grooming"],
        },
        {
          slug: "mattress-cleaning",
          title: "Mattress Cleaning",
          category: "Specialised Cleaning",
          image: "https://images.pexels.com/photos/14675103/pexels-photo-14675103.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Mattress cleaning to reduce dust buildup and refresh bedrooms with careful extraction methods.",
          includes: ["Mattress vacuuming", "Stain treatment", "Fabric-safe cleaning", "Drying instructions"],
        },
        {
          slug: "water-tank-cleaning",
          title: "Water Tank Cleaning",
          category: "Specialised Cleaning",
          image: "https://images.pexels.com/photos/25823811/pexels-photo-25823811.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/villa-cleaning-hq.png",
          summary: "Scheduled tank cleaning support for villas, apartments, and commercial properties.",
          includes: ["Tank inspection", "Sediment removal", "Interior cleaning", "Cleanliness check"],
        },
      ],
    },
    {
      id: "floor-care",
      label: "Marble & Floor care",
      eyebrow: "Stone and surface care",
      description: "Restoration, polishing, and stain treatment for marble, granite, and tired stone surfaces in homes and businesses.",
      background: "https://images.pexels.com/photos/14613453/pexels-photo-14613453.jpeg?auto=compress&cs=tinysrgb&w=1600",
      backgroundAlt: "Bright polished marble flooring in a modern interior",
      detailDefaults: {
        badges: ["Surface assessment", "Professional equipment", "Finish-care guidance"],
        spotlight: {
          kicker: "Specialist floor care",
          title: "A measured polishing or restoration plan for a cleaner, more refined floor finish.",
          copy: "Suitable for marble, granite, and tired stone surfaces in homes and commercial interiors.",
        },
        steps: [
          "We assess the floor type, current finish, stains, scratches, and worn areas.",
          "The team confirms the suitable polishing, treatment, or restoration process.",
          "We complete the work, review the finish, and provide practical maintenance guidance.",
        ],
        ctaLabel: "Request a floor assessment",
      },
      services: [
        {
          slug: "marble-polishing",
          title: "Marble Polishing",
          category: "Marble & Floor care",
          image: "https://images.pexels.com/photos/14613453/pexels-photo-14613453.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/marble-polishing-hq.png",
          summary: "Professional marble polishing for dull floors, worn surfaces, and premium interior finishes.",
          includes: ["Surface inspection", "Machine polishing", "Gloss restoration", "After-care guidance"],
        },
        {
          slug: "marble-restoration",
          title: "Marble Restoration",
          category: "Marble & Floor care",
          image: "https://images.pexels.com/photos/14225905/pexels-photo-14225905.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Restoration support for scratched, stained, or tired marble surfaces.",
          includes: ["Damage review", "Grinding or polishing plan", "Surface refinement", "Finish protection advice"],
        },
        {
          slug: "granite-polishing",
          title: "Granite Polishing",
          category: "Marble & Floor care",
          image: "https://images.pexels.com/photos/30112373/pexels-photo-30112373.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Granite polishing for homes, offices, entrances, countertops, and commercial interiors.",
          includes: ["Surface cleaning", "Polishing", "Edge attention", "Final finish review"],
        },
        {
          slug: "marble-stain-removal",
          title: "Marble Stain Removal",
          category: "Marble & Floor care",
          image: "https://images.pexels.com/photos/4440535/pexels-photo-4440535.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/marble-polishing-hq.png",
          summary: "Targeted stain removal support for common marks on marble and stone flooring.",
          includes: ["Stain assessment", "Treatment plan", "Careful removal process", "Prevention guidance"],
        },
      ],
    },
    {
      id: "pest-control",
      label: "Pest control service",
      eyebrow: "Inspection-led protection",
      description: "Targeted pest management for homes, commercial properties, cockroach concerns, and food-service environments.",
      background: "https://images.pexels.com/photos/4176415/pexels-photo-4176415.jpeg?auto=compress&cs=tinysrgb&w=1600",
      backgroundAlt: "Protective treatment being applied inside a property",
      detailDefaults: {
        badges: ["Inspection-led plan", "Targeted treatment", "Prevention guidance"],
        spotlight: {
          kicker: "Targeted pest protection",
          title: "A practical treatment plan focused on the pest, affected areas, and property type.",
          copy: "Support for homes, businesses, food-service spaces, and recurring pest concerns across Qatar.",
        },
        steps: [
          "Tell us what you have noticed and where activity is taking place.",
          "We inspect the affected and surrounding areas before confirming the treatment plan.",
          "The team applies the targeted treatment and explains safety and prevention guidance.",
        ],
        ctaLabel: "Book a pest inspection",
      },
      services: [
        {
          slug: "residential-pest-control",
          title: "Residential Pest Control",
          category: "Pest control service",
          image: "https://images.pexels.com/photos/4176415/pexels-photo-4176415.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/residential-pest-control-hq.png",
          summary: "Safe pest control for homes, villas, apartments, kitchens, bathrooms, and outdoor areas.",
          includes: ["Pest inspection", "Targeted treatment", "Safe-use guidance", "Follow-up recommendations"],
        },
        {
          slug: "commercial-pest-control",
          title: "Commercial Pest Control",
          category: "Pest control service",
          image: "https://images.pexels.com/photos/32055757/pexels-photo-32055757.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/commercial-pest-control-hq.png",
          summary: "Professional pest management for offices, shops, restaurants, warehouses, and shared facilities.",
          includes: ["Site inspection", "Treatment plan", "Discreet service visit", "Prevention checklist"],
        },
        {
          slug: "cockroach-control",
          title: "Cockroach Control",
          category: "Pest control service",
          image: "https://images.pexels.com/photos/6526933/pexels-photo-6526933.jpeg?auto=compress&cs=tinysrgb&w=900",
          detailImage: "public/service-showcase/enhanced/cockroaches-hq.png",
          summary: "Focused cockroach treatment for kitchens, drains, cabinets, and hidden harbourage areas.",
          includes: ["Infestation check", "Gel or spray treatment", "Entry-point guidance", "After-care steps"],
        },
        {
          slug: "restaurant-pest-control",
          title: "Restaurants & Cafes",
          category: "Pest control service",
          image: "https://images.pexels.com/photos/15441279/pexels-photo-15441279.jpeg?auto=compress&cs=tinysrgb&w=900",
          summary: "Hygiene-sensitive pest control for food service environments and customer-facing spaces.",
          includes: ["Kitchen and storage inspection", "Food-safe planning", "Targeted treatment", "Maintenance schedule advice"],
        },
      ],
    },
  ],
};

window.serviceCatalog.allServices = window.serviceCatalog.categories.flatMap((category) =>
  category.services.map((service) => ({
    ...service,
    categoryId: category.id,
  })),
);
