window.serviceCatalog = {
  categories: [
    {
      id: "cleaning",
      label: "Cleaning services",
      background: "public/service-showcase/figma-services-bg.png",
      backgroundAlt: "Professional cleaning service in a modern home",
      services: [
        {
          slug: "villa-cleaning",
          title: "Villa Cleaning",
          category: "Cleaning services",
          image: "public/service-showcase/villa-cleaning.png",
          summary: "Complete interior cleaning for villas, majlis rooms, kitchens, bathrooms, and daily living areas.",
          includes: ["Room-by-room dusting", "Floor mopping and vacuuming", "Kitchen and bathroom wipe-down", "Balcony and high-touch surface cleaning"],
        },
        {
          slug: "apartment-cleaning",
          title: "Apartment Cleaning",
          category: "Cleaning services",
          image: "public/figma-assets/image-5.png",
          summary: "Reliable apartment cleaning for compact homes, family flats, and rental handovers across Qatar.",
          includes: ["Bedroom and living area cleaning", "Kitchen counter cleaning", "Bathroom sanitising", "Trash removal and finishing checks"],
        },
        {
          slug: "majlis-cleaning",
          title: "Majlis Cleaning",
          category: "Cleaning services",
          image: "public/figma-assets/image-6.png",
          summary: "Careful cleaning for majlis spaces, seating areas, cushions, carpets, and guest-ready interiors.",
          includes: ["Soft furnishing vacuuming", "Surface dusting", "Floor care", "Detail cleaning before guest visits"],
          badges: ["Majlis seating care", "Fabric-safe cleaning", "Guest-ready finish"],
          facts: [
            { value: "2-4h", label: "Typical visit" },
            { value: "Soft", label: "Fabric-safe care" },
            { value: "Qatar", label: "Home service" },
          ],
          spotlight: {
            kicker: "Majlis-ready finish",
            title: "Fresh seating, cushions, carpets, and guest areas cleaned with care.",
            copy: "Ideal before family visits, gatherings, and regular majlis refreshes.",
          },
          steps: [
            "We review the majlis layout, seating fabric, cushions, carpets, and high-touch surfaces.",
            "Technicians vacuum, dust, spot-clean, and refresh the guest area with suitable methods.",
            "We complete a final check so the majlis is tidy, comfortable, and guest-ready.",
          ],
        },
        {
          slug: "kitchen-cleaning",
          title: "Kitchen Cleaning",
          category: "Cleaning services",
          image: "public/service-showcase/figma-services-bg.png",
          summary: "Focused kitchen cleaning for counters, cabinets, sinks, tiles, appliances, and daily cooking zones.",
          includes: ["Counter and sink cleaning", "Cabinet exterior wipe-down", "Tile and splashback cleaning", "Appliance exterior cleaning"],
        },
        {
          slug: "deep-cleaning",
          title: "Deep Cleaning",
          category: "Cleaning services",
          image: "public/figma-assets/image-7.png",
          summary: "A detailed cleaning visit for move-in, move-out, post-renovation, or seasonal refresh needs.",
          includes: ["Detailed dust removal", "Hard-to-reach areas", "Floor scrubbing", "Final inspection walkthrough"],
        },
      ],
    },
    {
      id: "specialised",
      label: "Specialised Cleaning",
      background: "public/service-showcase/sofa-cleaning.png",
      backgroundAlt: "Technician cleaning upholstery",
      services: [
        {
          slug: "sofa-cleaning",
          title: "Sofa Cleaning",
          category: "Specialised Cleaning",
          image: "public/service-showcase/sofa-cleaning.png",
          summary: "Fabric-safe sofa cleaning for stains, dust, odour, and everyday upholstery freshness.",
          includes: ["Fabric inspection", "Vacuum extraction", "Spot treatment", "Drying guidance"],
        },
        {
          slug: "carpet-cleaning",
          title: "Carpet Cleaning",
          category: "Specialised Cleaning",
          image: "public/figma-assets/image-7.png",
          summary: "Professional carpet care for homes, offices, majlis spaces, and high-traffic areas.",
          includes: ["Vacuuming", "Spot cleaning", "Machine cleaning", "Post-cleaning grooming"],
        },
        {
          slug: "mattress-cleaning",
          title: "Mattress Cleaning",
          category: "Specialised Cleaning",
          image: "public/figma-assets/image-6.png",
          summary: "Mattress cleaning to reduce dust buildup and refresh bedrooms with careful extraction methods.",
          includes: ["Mattress vacuuming", "Stain treatment", "Fabric-safe cleaning", "Drying instructions"],
        },
        {
          slug: "curtain-cleaning",
          title: "Curtain Cleaning",
          category: "Specialised Cleaning",
          image: "public/figma-assets/image-5.png",
          summary: "Curtain and drape cleaning support for dust, marks, and regular home maintenance.",
          includes: ["Fabric check", "Dust removal", "Spot care", "Gentle finishing"],
        },
        {
          slug: "water-tank-cleaning",
          title: "Water Tank Cleaning",
          category: "Specialised Cleaning",
          image: "public/service-showcase/villa-cleaning.png",
          summary: "Scheduled tank cleaning support for villas, apartments, and commercial properties.",
          includes: ["Tank inspection", "Sediment removal", "Interior cleaning", "Cleanliness check"],
        },
      ],
    },
    {
      id: "floor-care",
      label: "Marble & Floor care",
      background: "public/service-showcase/marble-polishing.png",
      backgroundAlt: "Marble floor polishing equipment",
      services: [
        {
          slug: "marble-polishing",
          title: "Marble Polishing",
          category: "Marble & Floor care",
          image: "public/service-showcase/marble-polishing.png",
          summary: "Professional marble polishing for dull floors, worn surfaces, and premium interior finishes.",
          includes: ["Surface inspection", "Machine polishing", "Gloss restoration", "After-care guidance"],
        },
        {
          slug: "marble-restoration",
          title: "Marble Restoration",
          category: "Marble & Floor care",
          image: "public/figma-assets/image-7.png",
          summary: "Restoration support for scratched, stained, or tired marble surfaces.",
          includes: ["Damage review", "Grinding or polishing plan", "Surface refinement", "Finish protection advice"],
        },
        {
          slug: "crystallization",
          title: "Crystallization",
          category: "Marble & Floor care",
          image: "public/service-showcase/marble-polishing.png",
          summary: "Crystallization treatment for stronger shine and a cleaner premium marble finish.",
          includes: ["Floor preparation", "Crystallization treatment", "Buffing", "Final gloss check"],
        },
        {
          slug: "granite-polishing",
          title: "Granite Polishing",
          category: "Marble & Floor care",
          image: "public/figma-assets/image-7.png",
          summary: "Granite polishing for homes, offices, entrances, countertops, and commercial interiors.",
          includes: ["Surface cleaning", "Polishing", "Edge attention", "Final finish review"],
        },
        {
          slug: "marble-stain-removal",
          title: "Marble Stain Removal",
          category: "Marble & Floor care",
          image: "public/service-showcase/marble-polishing.png",
          summary: "Targeted stain removal support for common marks on marble and stone flooring.",
          includes: ["Stain assessment", "Treatment plan", "Careful removal process", "Prevention guidance"],
        },
      ],
    },
    {
      id: "pest-control",
      label: "Pest control service",
      background: "public/figma-assets/image-4.png",
      backgroundAlt: "Outdoor pest control spraying treatment",
      services: [
        {
          slug: "residential-pest-control",
          title: "Residential Pest Control",
          category: "Pest control service",
          image: "public/service-showcase/residential-pest-control.png",
          summary: "Safe pest control for homes, villas, apartments, kitchens, bathrooms, and outdoor areas.",
          includes: ["Pest inspection", "Targeted treatment", "Safe-use guidance", "Follow-up recommendations"],
        },
        {
          slug: "commercial-pest-control",
          title: "Commercial Pest Control",
          category: "Pest control service",
          image: "public/service-showcase/commercial-pest-control.png",
          summary: "Professional pest management for offices, shops, restaurants, warehouses, and shared facilities.",
          includes: ["Site inspection", "Treatment plan", "Discreet service visit", "Prevention checklist"],
        },
        {
          slug: "cockroach-control",
          title: "Cockroach Control",
          category: "Pest control service",
          image: "public/service-showcase/cockroaches.png",
          summary: "Focused cockroach treatment for kitchens, drains, cabinets, and hidden harbourage areas.",
          includes: ["Infestation check", "Gel or spray treatment", "Entry-point guidance", "After-care steps"],
        },
        {
          slug: "restaurant-pest-control",
          title: "Restaurants & Cafes",
          category: "Pest control service",
          image: "public/figma-assets/image-4.png",
          summary: "Hygiene-sensitive pest control for food service environments and customer-facing spaces.",
          includes: ["Kitchen and storage inspection", "Food-safe planning", "Targeted treatment", "Maintenance schedule advice"],
        },
        {
          slug: "warehouse-pest-control",
          title: "Warehouses & Storage",
          category: "Pest control service",
          image: "public/service-showcase/residential-pest-control.png",
          summary: "Pest control support for storage facilities, stock rooms, warehouses, and back-of-house spaces.",
          includes: ["Perimeter inspection", "Treatment mapping", "Storage-zone treatment", "Prevention guidance"],
        },
      ],
    },
  ],
};

window.serviceCatalog.allServices = window.serviceCatalog.categories.flatMap((category) =>
  category.services.map((service) => ({
    ...service,
    categoryId: category.id,
  })),
);
